name: Deploy Backend

on: 
  push:
    branches:
      - main
      - backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # apni requirement ke hisab se

      - name: Install dependencies
        run: npm install

      - name: Start Backend
        run: |
          # Agar aapke backend me start script hai package.json me
          npm run start
        env:
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
